-- MySQL Script generated by MySQL Workbench
-- Tue Oct  6 19:23:41 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema TextiCol
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TextiCol
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TextiCol` DEFAULT CHARACTER SET utf8 ;
USE `TextiCol` ;

-- -----------------------------------------------------
-- Table `TextiCol`.`TipoClientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TextiCol`.`TipoClientes` ;

CREATE TABLE IF NOT EXISTS `TextiCol`.`TipoClientes` (
  `idTipoClientes` CHAR(2) NOT NULL,
  `NombreTipoCliente` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipoClientes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TextiCol`.`Clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TextiCol`.`Clientes` ;

CREATE TABLE IF NOT EXISTS `TextiCol`.`Clientes` (
  `idClientes` INT NOT NULL,
  `idTipoCliente` CHAR(2) NOT NULL,
  `Nombres` VARCHAR(45) NOT NULL,
  `Apellidos` VARCHAR(45) NOT NULL,
  `Direccion` VARCHAR(45) NOT NULL,
  `Telefono` INT NOT NULL,
  `Ciudad` VARCHAR(45) NOT NULL,
  `Correo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idClientes`),
  INDEX `TipoCliente_idx` (`idTipoCliente` ASC) VISIBLE,
  CONSTRAINT `TipoCliente`
    FOREIGN KEY (`idTipoCliente`)
    REFERENCES `TextiCol`.`TipoClientes` (`idTipoClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TextiCol`.`Productos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TextiCol`.`Productos` ;

CREATE TABLE IF NOT EXISTS `TextiCol`.`Productos` (
  `idProductos` INT NOT NULL,
  `NombreProducto` VARCHAR(45) NOT NULL,
  `Medida` VARCHAR(45) NOT NULL,
  `Stock` INT NOT NULL,
  `PrecioCompra` INT NULL,
  `PrecioVenta` INT NULL,
  PRIMARY KEY (`idProductos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TextiCol`.`Ventas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TextiCol`.`Ventas` ;

CREATE TABLE IF NOT EXISTS `TextiCol`.`Ventas` (
  `idVentas` INT NOT NULL,
  `idClientes` INT NOT NULL,
  `idProductos` INT NOT NULL,
  `CantidadProductos` INT NOT NULL,
  `FechaVenta` DATE NULL,
  `TotalVenta` INT NULL,
  PRIMARY KEY (`idVentas`),
  INDEX `idClientes_idx` (`idClientes` ASC) VISIBLE,
  INDEX `idProductos_idx` (`idProductos` ASC) VISIBLE,
  CONSTRAINT `idClientes`
    FOREIGN KEY (`idClientes`)
    REFERENCES `TextiCol`.`Clientes` (`idClientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idProductos`
    FOREIGN KEY (`idProductos`)
    REFERENCES `TextiCol`.`Productos` (`idProductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TextiCol`.`TipoReclamos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TextiCol`.`TipoReclamos` ;

CREATE TABLE IF NOT EXISTS `TextiCol`.`TipoReclamos` (
  `idTipoReclamos` CHAR(3) NOT NULL,
  `NombreReclamo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipoReclamos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TextiCol`.`Reclamos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TextiCol`.`Reclamos` ;

CREATE TABLE IF NOT EXISTS `TextiCol`.`Reclamos` (
  `idReclamos` INT NOT NULL,
  `idTipoReclamo` CHAR(3) NOT NULL,
  `Observacion` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`idReclamos`),
  INDEX `idTipoReclamo_idx` (`idTipoReclamo` ASC) VISIBLE,
  CONSTRAINT `idTipoReclamo`
    FOREIGN KEY (`idTipoReclamo`)
    REFERENCES `TextiCol`.`TipoReclamos` (`idTipoReclamos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TextiCol`.`Obligaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TextiCol`.`Obligaciones` ;

CREATE TABLE IF NOT EXISTS `TextiCol`.`Obligaciones` (
  `idObligaciones` INT NOT NULL,
  `NombreObligacion` VARCHAR(45) NOT NULL,
  `Descripcion` VARCHAR(200) NOT NULL,
  `TotalObligacion` INT NOT NULL,
  PRIMARY KEY (`idObligaciones`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TextiCol`.`Informes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TextiCol`.`Informes` ;

CREATE TABLE IF NOT EXISTS `TextiCol`.`Informes` (
  `idInformes` INT NOT NULL,
  `idVentas` INT NOT NULL,
  `idObligaciones` INT NOT NULL,
  `idReclamos` INT NOT NULL,
  `TotalVentas` INT NULL,
  `TotalPedidos` INT NULL,
  `TotalObligaciones` INT NULL,
  `Utilidades` INT NULL,
  `FechaInforme` DATE NULL,
  PRIMARY KEY (`idInformes`),
  INDEX `idVentas_idx` (`idVentas` ASC) VISIBLE,
  INDEX `idObligaciones_idx` (`idObligaciones` ASC) VISIBLE,
  INDEX `idReclamos_idx` (`idReclamos` ASC) VISIBLE,
  CONSTRAINT `idVentas`
    FOREIGN KEY (`idVentas`)
    REFERENCES `TextiCol`.`Ventas` (`idVentas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idObligaciones`
    FOREIGN KEY (`idObligaciones`)
    REFERENCES `TextiCol`.`Obligaciones` (`idObligaciones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idReclamos`
    FOREIGN KEY (`idReclamos`)
    REFERENCES `TextiCol`.`Reclamos` (`idReclamos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TextiCol`.`TipoPagos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TextiCol`.`TipoPagos` ;

CREATE TABLE IF NOT EXISTS `TextiCol`.`TipoPagos` (
  `idTipoPagos` INT NOT NULL,
  `NombreTipoPago` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipoPagos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TextiCol`.`Pedidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TextiCol`.`Pedidos` ;

CREATE TABLE IF NOT EXISTS `TextiCol`.`Pedidos` (
  `idTipoPagos` INT NOT NULL,
  `idVentas` INT NOT NULL,
  `FechaEntrega` DATE NULL,
  INDEX `idTipoPagos_idx` (`idTipoPagos` ASC) VISIBLE,
  INDEX `idVentas_idx` (`idVentas` ASC) VISIBLE,
  CONSTRAINT `idTipoPagos`
    FOREIGN KEY (`idTipoPagos`)
    REFERENCES `TextiCol`.`TipoPagos` (`idTipoPagos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idVentas`
    FOREIGN KEY (`idVentas`)
    REFERENCES `TextiCol`.`Ventas` (`idVentas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
